# Generated by Django 5.1.4 on 2025-01-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='hhVYsUk7ujAfsNp0X6ch6IDrdK9Qjn7h', editable=False, max_length=32, unique=True),
        ),
    ]
